export const books = [
  // ─────────────────────────────────────────
  // 🧠 SELF DEVELOPMENT
  // ─────────────────────────────────────────

  {
    id: 1,
    title: "atomic habits",
    author: "James Clear",
    header:
      "the #1 new york times bestseller. over 25 million copies sold! translated into 60+ languages!",
    subheader: "tiny changes, remarkable results",
    description:
      "james clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results. if you're having trouble changing your habits, the problem isn't you — the problem is your system. you do not rise to the level of your goals. you fall to the level of your systems.",
    coverImage: "",
    primaryCollection: "lead me",
    collections: ["lead me", "lead him", "lead her"],
    genre: "self development",
    price: { paperback: 1900000, hardback: 3000000 },
    rating: 4.8,
    reviews: 890,
    tag: ["classic", "bestseller"],
  },

  {
    id: 2,
    title: "the 7 habits of highly effective people",
    author: "Stephen Covey",
    header: "one of the most inspiring and impactful books ever written",
    subheader: "powerful lessons in personal change",
    description:
      "stephen covey presents a holistic, integrated, principle-centered approach for solving personal and professional problems. with penetrating insights and pointed anecdotes, covey reveals a step-by-step pathway for living with fairness, integrity, honesty, and human dignity — principles that give us the security to adapt to change and the wisdom and power to take advantage of the opportunities that change creates.",
    coverImage: "",
    primaryCollection: "lead me",
    collections: ["lead me", "lead him"],
    genre: "self development",
    price: { paperback: 1800000, hardback: 2800000 },
    rating: 4.7,
    reviews: 1200,
    tag: ["classic", "bestseller"],
  },

  {
    id: 3,
    title: "mindset",
    author: "Carol Dweck",
    header: "the new psychology of success",
    subheader: "how we can learn to fulfill our potential",
    description:
      "after decades of research, world-renowned stanford university psychologist carol s. dweck discovered a simple but groundbreaking idea: the power of mindset. in this book, she shows how success in school, work, sports, the arts, and almost every area of human endeavor can be dramatically influenced by how we think about our talents and abilities.",
    coverImage: "",
    primaryCollection: "lead me",
    collections: ["lead me", "lead her"],
    genre: "self development",
    price: { paperback: 1700000, hardback: 2600000 },
    rating: 4.6,
    reviews: 980,
    tag: ["bestseller"],
  },

  {
    id: 4,
    title: "think and grow rich",
    author: "Napoleon Hill",
    header:
      "the landmark bestseller now revised and updated for the 21st century",
    subheader: "the secret to success is in your mind",
    description:
      "think and grow rich has been called the granddaddy of all motivational literature. it was the first book to boldly ask, what makes a winner? napoleon hill studied more than 500 of america's most successful individuals and discovered that great wealth begins with a state of mind — not with money, education, or luck.",
    coverImage: "",
    primaryCollection: "lead me",
    collections: ["lead me", "lead him", "lead with money"],
    genre: "self development",
    price: { paperback: 1600000, hardback: 2500000 },
    rating: 4.6,
    reviews: 2100,
    tag: ["classic", "bestseller"],
  },

  {
    id: 5,
    title: "the subtle art of not giving a f*ck",
    author: "Mark Manson",
    header:
      "a #1 new york times bestseller. over 12 million copies sold worldwide.",
    subheader: "a counterintuitive approach to living a good life",
    description:
      "for decades we've been told that positive thinking is the key to a happy, rich life. mark manson says this is nonsense. he makes the argument, backed by both academic research and well-timed humor, that improving our lives hinges not on turning lemons into lemonade, but on learning to stomach lemons better. the key to a good life is not giving a f*ck about more — it's giving a f*ck about less.",
    coverImage: "",
    primaryCollection: "lead me",
    collections: ["lead me", "lead him"],
    genre: "self development",
    price: { paperback: 1800000, hardback: 2800000 },
    rating: 4.5,
    reviews: 3200,
    tag: ["bestseller"],
  },

  {
    id: 6,
    title: "how to win friends & influence people",
    author: "Dale Carnegie",
    header: "the most famous confidence-building book ever published",
    subheader: "over 30 million copies sold worldwide",
    description:
      "originally published in 1936, dale carnegie's rock-solid, time-tested advice has carried countless people up the ladder of success in their professional and personal lives. this book teaches you how to communicate effectively, make people like you, get others to see your side, become a more effective leader, and successfully navigate almost any social situation.",
    coverImage: "",
    primaryCollection: "lead me",
    collections: ["lead me", "lead them"],
    genre: "self development",
    price: { paperback: 1600000, hardback: 2500000 },
    rating: 4.7,
    reviews: 4500,
    tag: ["classic", "bestseller"],
  },

  {
    id: 7,
    title: "can't hurt me",
    author: "David Goggins",
    header: "master your mind and defy the odds",
    subheader: "the inspiring story of self-mastery and mental toughness",
    description:
      "for david goggins, childhood was a nightmare — poverty, prejudice, and physical abuse colored his days and haunted his nights. but through self-discipline, mental toughness, and hard work, goggins transformed himself from a depressed, overweight young man into a us armed forces icon and one of the world's top endurance athletes. his story shows that most of us only tap into 40% of our capabilities.",
    coverImage: "",
    primaryCollection: "lead him",
    collections: ["lead him", "lead me"],
    genre: "self development",
    price: { paperback: 1900000, hardback: 3000000 },
    rating: 4.9,
    reviews: 3100,
    tag: ["bestseller", "top rated"],
  },

  {
    id: 8,
    title: "deep work",
    author: "Cal Newport",
    header: "rules for focused success in a distracted world",
    subheader: "the ability to focus without distraction is a superpower",
    description:
      "deep work is the ability to focus without distraction on cognitively demanding tasks. cal newport argues that this skill is becoming increasingly rare at exactly the same time it is becoming increasingly valuable. the few who cultivate this skill and make it the core of their work life will thrive.",
    coverImage: "",
    primaryCollection: "lead me",
    collections: ["lead me", "lead them"],
    genre: "self development",
    price: { paperback: 1800000, hardback: 2700000 },
    rating: 4.7,
    reviews: 760,
    tag: ["staff pick"],
  },

  {
    id: 9,
    title: "the power of habit",
    author: "Charles Duhigg",
    header: "why we do what we do in life and business",
    subheader: "habits can be changed if we understand how they work",
    description:
      "pulitzer prize-winning journalist charles duhigg takes us to the thrilling edge of scientific discoveries that explain why habits exist and how they can be changed. with penetrating intelligence, duhigg brings to life a whole new understanding of human nature and its potential for transformation.",
    coverImage: "",
    primaryCollection: "lead me",
    collections: ["lead me", "lead them"],
    genre: "self development",
    price: { paperback: 1800000, hardback: 2700000 },
    rating: 4.6,
    reviews: 1400,
    tag: ["bestseller"],
  },

  {
    id: 10,
    title: "man's search for meaning",
    author: "Viktor Frankl",
    header: "one of the ten most influential books in america",
    subheader: "a psychiatrist's path to a new therapy",
    description:
      "psychiatrist viktor frankl survived the nazi concentration camps and emerged with a profound insight: even in the most extreme suffering, humans can find meaning. his experiences led him to develop logotherapy — the belief that the primary human motivation is the search for meaning in life. this book is both a memoir of survival and a guide to discovering your own purpose.",
    coverImage: "",
    primaryCollection: "lead me",
    collections: ["lead me"],
    genre: "self development",
    price: { paperback: 1500000, hardback: 2400000 },
    rating: 4.8,
    reviews: 5200,
    tag: ["classic", "top rated"],
  },

  {
    id: 11,
    title: "a-z of personal finance",
    author: "Nimi Akinkugbe",
    header: "nigeria's most trusted guide to personal wealth management",
    subheader:
      "practical information and useful tips on matters concerning you and your money",
    description:
      "with a professional career spanning over two decades in banking and private wealth management, nimi akinkugbe provides important practical information and useful tips on all matters concerning you and your money. whether you are just starting out, approaching retirement, or somewhere in between, this book will help you take control of your financial future — written specifically with the nigerian context in mind.",
    coverImage: "",
    primaryCollection: "lead with money",
    collections: ["lead with money", "lead me"],
    genre: "self development",
    price: { paperback: 1500000, hardback: 2400000 },
    rating: 4.5,
    reviews: 210,
    tag: ["staff pick"],
  },

  {
    id: 12,
    title: "thoughts from a wealthy perspective",
    author: "Samuel Egube",
    header: "a nigerian guide to building wealth and financial freedom",
    subheader: "the mindset and strategies of the financially free",
    description:
      "samuel egube, one of nigeria's foremost economists and financial experts, shares his insights on wealth creation, financial planning, and the mindset required to build lasting prosperity in the nigerian context. a practical and inspiring guide for anyone ready to take their finances seriously.",
    coverImage: "",
    primaryCollection: "lead with money",
    collections: ["lead with money", "lead me"],
    genre: "self development",
    price: { paperback: 1600000, hardback: 2500000 },
    rating: 4.4,
    reviews: 180,
    tag: ["staff pick"],
  },

  {
    id: 13,
    title: "the four agreements",
    author: "Don Miguel Ruiz",
    header: "a practical guide to personal freedom",
    subheader: "a toltec wisdom book",
    description:
      "in the four agreements, don miguel ruiz reveals the source of self-limiting beliefs that rob us of joy and create needless suffering. based on ancient toltec wisdom, the four agreements offer a powerful code of conduct that can rapidly transform our lives to a new experience of freedom, true happiness, and love.",
    coverImage: "",
    primaryCollection: "lead me",
    collections: ["lead me"],
    genre: "self development",
    price: { paperback: 1600000, hardback: 2500000 },
    rating: 4.6,
    reviews: 3800,
    tag: ["classic", "bestseller"],
  },

  {
    id: 14,
    title: "getting things done",
    author: "David Allen",
    header: "the art of stress-free productivity",
    subheader: "the definitive guide to personal and professional productivity",
    description:
      "for more than twenty years, the time-tested methods of david allen's getting things done have helped countless professionals around the world manage the ever-increasing demands of their workplaces. allen reveals how to capture everything that needs to get done into a logical and trusted system, so you always have a plan for next actions.",
    coverImage: "",
    primaryCollection: "lead me",
    collections: ["lead me"],
    genre: "self development",
    price: { paperback: 1700000, hardback: 2600000 },
    rating: 4.5,
    reviews: 890,
    tag: ["classic"],
  },

  {
    id: 15,
    title: "thinking fast and slow",
    author: "Daniel Kahneman",
    header: "the #1 international bestseller",
    subheader: "a revolutionary look at the way your mind works",
    description:
      "in this work, nobel prize-winning economist daniel kahneman takes us on a groundbreaking tour of the mind, explaining the two systems that drive the way we think. system 1 is fast, intuitive, and emotional; system 2 is slower, more deliberative, and more logical. kahneman exposes the extraordinary capabilities and faults and biases of fast thinking.",
    coverImage: "",
    primaryCollection: "lead me",
    collections: ["lead me", "lead them"],
    genre: "self development",
    price: { paperback: 1900000, hardback: 3000000 },
    rating: 4.6,
    reviews: 2400,
    tag: ["classic", "bestseller"],
  },

  // ─────────────────────────────────────────
  // 💼 BUSINESS & LEADERSHIP
  // ─────────────────────────────────────────

  {
    id: 16,
    title: "africa rise and shine",
    author: "Jim Ovia",
    header:
      "how a nigerian entrepreneur built a bank and helped build a nation",
    subheader: "the inspiring story of zenith bank's founder",
    description:
      "jim ovia, founder of zenith bank — one of africa's most successful financial institutions — shares his extraordinary story of building a world-class bank from scratch in nigeria. from humble beginnings to becoming one of africa's most influential business leaders, ovia shares hard-won lessons about entrepreneurship, perseverance, and nation-building in emerging markets.",
    coverImage: "",
    primaryCollection: "lead them",
    collections: ["lead them", "lead with money", "lead with legacy"],
    genre: "business & leadership",
    price: { paperback: 2100000, hardback: 3300000 },
    rating: 4.8,
    reviews: 450,
    tag: ["staff pick"],
  },

  {
    id: 17,
    title: "leaving the tarmac",
    author: "Aigboje Aig-Imoukhuede",
    header: "the most compelling business success story to come out of africa",
    subheader: "buying a bank in africa",
    description:
      "when aigboje aig-imoukhuede and herbert wigwe bought access bank in 2002, it was one of the smallest and most crisis-prone banks in nigeria. their goal was to build it into one of the biggest and strongest banks on the continent. leaving the tarmac reads like a financial thriller, while providing a detailed blueprint for how to create a sustainable business in emerging african markets.",
    coverImage: "",
    primaryCollection: "lead them",
    collections: ["lead them", "lead with money", "lead with legacy"],
    genre: "business & leadership",
    price: { paperback: 2000000, hardback: 3100000 },
    rating: 4.7,
    reviews: 310,
    tag: ["staff pick"],
  },

  {
    id: 18,
    title: "the girls in the boardroom",
    author: "Ibukun Awosika",
    header: "lessons from africa's most celebrated businesswoman",
    subheader: "breaking barriers and building legacies",
    description:
      "ibukun awosika, one of africa's most celebrated business leaders and former chairperson of first bank of nigeria, shares her remarkable journey and the lessons she has learned from decades at the top of corporate nigeria. a powerful guide for every woman who dares to lead.",
    coverImage: "",
    primaryCollection: "lead her",
    collections: ["lead her", "lead them", "lead with legacy"],
    genre: "business & leadership",
    price: { paperback: 1800000, hardback: 2800000 },
    rating: 4.7,
    reviews: 320,
    tag: ["staff pick"],
  },

  {
    id: 19,
    title: "who says you can't?",
    author: "Frank Nneji",
    header:
      "the inspiring story of one of nigeria's most successful entrepreneurs",
    subheader: "building a business against all odds",
    description:
      "frank nneji, founder of abc transport, shares the story of how he built one of nigeria's most successful transport companies from almost nothing. this honest and inspiring memoir is a blueprint for entrepreneurs across africa who dare to dream big and refuse to accept that success is out of reach.",
    coverImage: "",
    primaryCollection: "lead them",
    collections: ["lead them", "lead me"],
    genre: "business & leadership",
    price: { paperback: 1700000, hardback: 2700000 },
    rating: 4.5,
    reviews: 230,
    tag: ["staff pick"],
  },

  {
    id: 20,
    title: "africa's business revolution",
    author: "Acha Leke",
    header: "how to succeed in the world's next big growth market",
    subheader: "a guide to doing business in africa",
    description:
      "africa is the world's next great growth market, and business leaders who understand it stand to gain enormously. acha leke and his co-authors draw on decades of research and fieldwork across the continent to reveal how africa's most successful companies are built — and provide a practical roadmap for any business looking to invest, grow, and lead in africa.",
    coverImage: "",
    primaryCollection: "lead them",
    collections: ["lead them", "lead the world"],
    genre: "business & leadership",
    price: { paperback: 2200000, hardback: 3400000 },
    rating: 4.6,
    reviews: 280,
    tag: ["staff pick"],
  },

  {
    id: 21,
    title: "good to great",
    author: "Jim Collins",
    header: "why some companies make the leap and others don't",
    subheader: "the definitive management study of our time",
    description:
      "built on a five-year research project, good to great answers the question: can a good company become a great company, and if so, how? jim collins and his team identified elite companies that made the leap to great results and sustained them for at least fifteen years. the findings challenge many of the conventional notions of corporate success.",
    coverImage: "",
    primaryCollection: "lead them",
    collections: ["lead them", "lead with money"],
    genre: "business & leadership",
    price: { paperback: 2000000, hardback: 3200000 },
    rating: 4.8,
    reviews: 2100,
    tag: ["classic", "bestseller"],
  },

  {
    id: 22,
    title: "start with why",
    author: "Simon Sinek",
    header: "how great leaders inspire everyone to take action",
    subheader: "the inspiring story behind the golden circle",
    description:
      "why are some people and organizations more innovative, more influential, and more profitable than others? simon sinek shows that the leaders who have had the greatest influence in the world all think, act and communicate the same way — starting with why. it's the key to inspiring those around you.",
    coverImage: "",
    primaryCollection: "lead them",
    collections: ["lead them", "lead me"],
    genre: "business & leadership",
    price: { paperback: 1900000, hardback: 2900000 },
    rating: 4.7,
    reviews: 1650,
    tag: ["bestseller"],
  },

  {
    id: 23,
    title: "leaders eat last",
    author: "Simon Sinek",
    header: "why some teams pull together and others don't",
    subheader: "the secret of great leadership is sacrifice",
    description:
      "simon sinek investigates the cultures of the best organizations in the world and finds a common thread: the leaders create environments in which people naturally work together to do remarkable things. drawing on examples from the us marines to wall street, sinek shows that the best leaders sacrifice their own comfort for the good of those in their care.",
    coverImage: "",
    primaryCollection: "lead them",
    collections: ["lead them", "lead him"],
    genre: "business & leadership",
    price: { paperback: 1900000, hardback: 2900000 },
    rating: 4.6,
    reviews: 1100,
    tag: ["bestseller"],
  },

  {
    id: 24,
    title: "zero to one",
    author: "Peter Thiel",
    header: "notes on startups, or how to build the future",
    subheader: "the bible of startup thinking",
    description:
      "peter thiel, co-founder of paypal and palantir, shares his unconventional wisdom on building companies that create something genuinely new. every moment in business happens only once — the next bill gates will not build an operating system, the next mark zuckerberg won't create a social network. creating something truly new takes it from 0 to 1.",
    coverImage: "",
    primaryCollection: "lead with money",
    collections: ["lead with money", "lead them"],
    genre: "business & leadership",
    price: { paperback: 1900000, hardback: 2900000 },
    rating: 4.5,
    reviews: 1800,
    tag: ["bestseller"],
  },

  {
    id: 25,
    title: "the hard thing about hard things",
    author: "Ben Horowitz",
    header: "building a business when there are no easy answers",
    subheader: "the most honest book about entrepreneurship ever written",
    description:
      "ben horowitz, co-founder of andreessen horowitz, draws on his decades of experience as a ceo and investor to offer essential advice on building and running a startup. in this honest account, he describes the challenges that come with founding, building, managing, and selling a business — and explains why there's no formula for success.",
    coverImage: "",
    primaryCollection: "lead them",
    collections: ["lead them"],
    genre: "business & leadership",
    price: { paperback: 2000000, hardback: 3100000 },
    rating: 4.7,
    reviews: 980,
    tag: ["staff pick"],
  },

  {
    id: 26,
    title: "how to sell to nigerians",
    author: "Akin Alabi",
    header: "win more customers, make more money",
    subheader: "the ultimate guide to selling in the nigerian market",
    description:
      "akin alabi, one of nigeria's most successful digital marketers and entrepreneurs, reveals the unique psychology of the nigerian consumer and how to craft messages that convert. packed with practical examples and real-world strategies tested in the nigerian market, this is essential reading for anyone selling in nigeria.",
    coverImage: "",
    primaryCollection: "lead with money",
    collections: ["lead with money", "lead them"],
    genre: "business & leadership",
    price: { paperback: 1500000, hardback: 2400000 },
    rating: 4.6,
    reviews: 380,
    tag: ["staff pick", "new arrival"],
  },

  {
    id: 27,
    title: "dare to lead",
    author: "Brené Brown",
    header: "brave work. tough conversations. whole hearts.",
    subheader: "the ultimate guide to courageous leadership",
    description:
      "leadership is not about titles, status, and wielding power. a leader is anyone who takes responsibility for recognizing the potential in people and ideas, and has the courage to develop that potential. brené brown shows that the most transformational leaders are those who have the courage to be vulnerable.",
    coverImage: "",
    primaryCollection: "lead her",
    collections: ["lead her", "lead them", "lead me"],
    genre: "business & leadership",
    price: { paperback: 1900000, hardback: 3000000 },
    rating: 4.7,
    reviews: 987,
    tag: ["bestseller", "staff pick"],
  },

  {
    id: 28,
    title: "the lean startup",
    author: "Eric Ries",
    header:
      "how today's entrepreneurs use continuous innovation to create radically successful businesses",
    subheader: "a new approach for the age of uncertainty",
    description:
      "eric ries introduces the lean startup method, a scientific approach to creating and managing startups that gets the desired product to customers' hands faster. by validating assumptions and adapting based on feedback, entrepreneurs can reduce market risks and sidestep the need for large amounts of initial funding.",
    coverImage: "",
    primaryCollection: "lead them",
    collections: ["lead them", "lead with money"],
    genre: "business & leadership",
    price: { paperback: 1900000, hardback: 2900000 },
    rating: 4.5,
    reviews: 1300,
    tag: ["bestseller"],
  },

  {
    id: 29,
    title: "built to last",
    author: "Jim Collins",
    header: "successful habits of visionary companies",
    subheader:
      "the ultimate business book about building enduring great companies",
    description:
      "drawing on a six-year research project at stanford university, jim collins and jerry porras studied eighteen truly exceptional and long-lasting companies and compared each directly to a top competitor. the findings revealed key underlying principles that enabled visionary companies to be successful across many decades.",
    coverImage: "",
    primaryCollection: "lead them",
    collections: ["lead them"],
    genre: "business & leadership",
    price: { paperback: 2000000, hardback: 3100000 },
    rating: 4.6,
    reviews: 890,
    tag: ["classic"],
  },

  {
    id: 30,
    title: "purple cow",
    author: "Seth Godin",
    header: "transform your business by being remarkable",
    subheader: "you're either a purple cow or you're not",
    description:
      "you're either a purple cow or you're not. you're either remarkable or invisible. in purple cow, seth godin urges you to put a purple cow into everything you build and everything you do — to create something truly noticeable. the old ps of marketing are no longer sufficient. standing out is the only option.",
    coverImage: "",
    primaryCollection: "lead them",
    collections: ["lead them", "lead with money"],
    genre: "business & leadership",
    price: { paperback: 1700000, hardback: 2600000 },
    rating: 4.4,
    reviews: 760,
    tag: ["classic"],
  },

  // ─────────────────────────────────────────
  // 👤 BIOGRAPHY
  // ─────────────────────────────────────────

  {
    id: 31,
    title: "steve jobs",
    author: "Walter Isaacson",
    header: "the exclusive biography of apple's founder",
    subheader: "the man who thought different",
    description:
      "based on more than forty interviews with jobs conducted over two years — as well as interviews with more than a hundred family members, friends, adversaries, and colleagues — walter isaacson has written a riveting story of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy", "lead them"],
    genre: "biography",
    price: { paperback: 2200000, hardback: 3500000 },
    rating: 4.7,
    reviews: 2890,
    tag: ["classic", "bestseller"],
  },

  {
    id: 32,
    title: "elon musk",
    author: "Walter Isaacson",
    header: "the story of the world's most audacious entrepreneur",
    subheader: "a biography of the man reshaping our future",
    description:
      "walter isaacson's riveting biography of elon musk explores how his turbulent upbringing in south africa shaped the drive, vision, and uncompromising personality that has made him both one of the most influential people alive and one of the most controversial. it covers his work at tesla, spacex, twitter, and beyond.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy", "lead with money"],
    genre: "biography",
    price: { paperback: 2300000, hardback: 3600000 },
    rating: 4.5,
    reviews: 1430,
    tag: ["new arrival", "bestseller"],
  },

  {
    id: 33,
    title: "long walk to freedom",
    author: "Nelson Mandela",
    header: "the autobiography of nelson mandela",
    subheader: "the inspiring life story of south africa's greatest leader",
    description:
      "the autobiography of nelson mandela — the statesman who emerged from 27 years in prison to lead his country out of apartheid and become its first democratically elected president. mandela's story is one of the most inspiring of our time — a story of integrity, courage, and determination in the face of overwhelming injustice.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy", "lead the world"],
    genre: "biography",
    price: { paperback: 2000000, hardback: 3200000 },
    rating: 4.9,
    reviews: 3400,
    tag: ["classic", "top rated"],
  },

  {
    id: 34,
    title: "africa rise and shine",
    author: "Jim Ovia",
    header: "the story of one of africa's greatest entrepreneurs",
    subheader: "building a world-class bank in nigeria",
    description:
      "jim ovia chronicles the building of zenith bank into one of the most successful financial institutions in africa. this biography reads as both a personal success story and a blueprint for building enduring institutions in africa's challenging but high-growth environment.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy", "lead them"],
    genre: "biography",
    price: { paperback: 2100000, hardback: 3300000 },
    rating: 4.8,
    reviews: 450,
    tag: ["staff pick"],
  },

  {
    id: 35,
    title: "alexander hamilton",
    author: "Ron Chernow",
    header: "the pulitzer prize-winning biography",
    subheader: "the story of america's most dynamic founding father",
    description:
      "ron chernow's landmark biography of alexander hamilton reveals the turbulent life of the genius who shaped the modern united states. illegitimate and orphaned, hamilton rose to become george washington's aide-de-camp, a founding father, and the nation's first treasury secretary — all while struggling with fierce political rivalries and the tragic duel that ended his life.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy"],
    genre: "biography",
    price: { paperback: 2400000, hardback: 3800000 },
    rating: 4.8,
    reviews: 2100,
    tag: ["classic", "top rated"],
  },

  {
    id: 36,
    title: "leonardo da vinci",
    author: "Walter Isaacson",
    header: "a biography of history's greatest creative genius",
    subheader:
      "the passionate, creative, and eccentric genius who helped define the renaissance",
    description:
      "based on thousands of pages from leonardo's astonishing notebooks and on new discoveries about his life and work, walter isaacson weaves a narrative that connects his art to his science. he shows how leonardo's genius was based on skills we can improve in ourselves — insatiable curiosity, careful observation, and a playful imagination.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy"],
    genre: "biography",
    price: { paperback: 2300000, hardback: 3600000 },
    rating: 4.7,
    reviews: 1200,
    tag: ["bestseller"],
  },

  {
    id: 37,
    title: "napoleon",
    author: "Andrew Roberts",
    header: "a life — the definitive biography of a complex genius",
    subheader:
      "the most authoritative and compelling biography of napoleon ever written",
    description:
      "andrew roberts's napoleon is the first one-volume biography to take advantage of the recently discovered 33,000 letters napoleon wrote throughout his life. his portrait demolishes the myths — revealing a brilliant general, a pragmatic statesman, and in many ways a visionary man of his era.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy", "lead the world"],
    genre: "biography",
    price: { paperback: 2400000, hardback: 3800000 },
    rating: 4.7,
    reviews: 890,
    tag: ["bestseller"],
  },

  {
    id: 38,
    title: "einstein",
    author: "Walter Isaacson",
    header: "his life and universe",
    subheader: "the story of the most famous scientist who ever lived",
    description:
      "drawing on newly released personal letters and previously classified files, walter isaacson unlocks the mystery of einstein's genius and illuminates an inspirational story of creativity and courage. it is the story of a rebellious spirit who discovered the theory of relativity and became the iconic genius of the twentieth century.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy"],
    genre: "biography",
    price: { paperback: 2200000, hardback: 3500000 },
    rating: 4.7,
    reviews: 1100,
    tag: ["bestseller"],
  },

  {
    id: 39,
    title: "african entrepreneurs & their success stories",
    author: "Various Authors",
    header: "the untold stories of africa's most inspiring business builders",
    subheader: "real lessons from real african entrepreneurs",
    description:
      "a compelling collection of stories from entrepreneurs across the african continent who defied the odds to build successful businesses. from lagos to nairobi, accra to johannesburg, these stories reveal the grit, creativity, and resilience that define the new generation of african business leaders.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy", "lead them"],
    genre: "biography",
    price: { paperback: 1800000, hardback: 2800000 },
    rating: 4.4,
    reviews: 180,
    tag: ["staff pick", "new arrival"],
  },

  {
    id: 40,
    title: "churchill",
    author: "Roy Jenkins",
    header:
      "the masterful, defining biography of the greatest political figure of the 20th century",
    subheader: "the man who saved the world",
    description:
      "roy jenkins — himself one of the most distinguished politicians of the twentieth century — wrote this acclaimed biography after coming to know many of the people who had known churchill personally. it is a brilliantly written portrait of one of history's most complex, flawed, and ultimately heroic leaders.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy", "lead the world"],
    genre: "biography",
    price: { paperback: 2300000, hardback: 3600000 },
    rating: 4.6,
    reviews: 670,
    tag: ["classic"],
  },

  // ─────────────────────────────────────────
  // ✍️ MEMOIR
  // ─────────────────────────────────────────

  {
    id: 41,
    title: "becoming",
    author: "Michelle Obama",
    header:
      "an intimate, powerful, and inspiring memoir by the former first lady of the united states",
    subheader: "in her own words",
    description:
      "in a life filled with meaning and accomplishment, michelle obama has emerged as one of the most iconic and compelling women of our era. as the first african american first lady of the united states, she helped create the most welcoming white house in history while establishing herself as a powerful advocate for women and girls around the world.",
    coverImage: "",
    primaryCollection: "lead her",
    collections: ["lead her", "lead with legacy"],
    genre: "memoir",
    price: { paperback: 2000000, hardback: 3200000 },
    rating: 4.9,
    reviews: 4200,
    tag: ["bestseller", "top rated"],
  },

  {
    id: 42,
    title: "shoe dog",
    author: "Phil Knight",
    header: "a memoir by the creator of nike",
    subheader: "the story of how nike was built from the ground up",
    description:
      "in this candid and riveting memoir, nike founder phil knight shares the inside story of the company's early days as an idea and then a fledgling business, and how it grew to become one of the world's most iconic and profitable brands. it is an honest account of near-bankruptcy, betrayal, perseverance, and the courage it takes to build something from nothing.",
    coverImage: "",
    primaryCollection: "lead with money",
    collections: ["lead with money", "lead him", "lead with legacy"],
    genre: "memoir",
    price: { paperback: 1900000, hardback: 3000000 },
    rating: 4.8,
    reviews: 2100,
    tag: ["bestseller", "staff pick"],
  },

  {
    id: 43,
    title: "open",
    author: "Andre Agassi",
    header: "a new york times bestselling memoir",
    subheader:
      "the most honest, revealing book any professional athlete has ever written",
    description:
      "from the first page of this extraordinary memoir, andre agassi admits that he hates tennis. and yet he keeps playing — driven by a domineering father, a desire to escape poverty, and the desperate need to justify his existence. this candid memoir spans agassi's entire life and career, including his personal struggles and ultimate redemption.",
    coverImage: "",
    primaryCollection: "lead him",
    collections: ["lead him", "lead with legacy"],
    genre: "memoir",
    price: { paperback: 1800000, hardback: 2900000 },
    rating: 4.7,
    reviews: 1400,
    tag: ["bestseller"],
  },

  {
    id: 44,
    title: "a promised land",
    author: "Barack Obama",
    header: "a riveting, deeply personal account of history in the making",
    subheader: "the story of one man's journey to the oval office",
    description:
      "in the stirring first volume of his presidential memoirs, barack obama tells the story of his improbable odyssey from young man searching for his identity to leader of the free world. describing in striking personal detail both his political education and the landmark moments of the first term of his historic presidency.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy", "lead the world"],
    genre: "memoir",
    price: { paperback: 2200000, hardback: 3500000 },
    rating: 4.8,
    reviews: 1800,
    tag: ["bestseller"],
  },

  {
    id: 45,
    title: "pour your heart into it",
    author: "Howard Schultz",
    header: "how starbucks built a company one cup at a time",
    subheader:
      "the story of one of the most remarkable business ventures of our time",
    description:
      "howard schultz tells the story of how he turned a commodity into a cultural phenomenon. this memoir traces the growth of starbucks from a single seattle coffee shop into a global empire — revealing the principles that guided schultz in building the company and how he put passion above the pressure of immediate profits.",
    coverImage: "",
    primaryCollection: "lead with money",
    collections: ["lead with money", "lead with legacy"],
    genre: "memoir",
    price: { paperback: 1800000, hardback: 2800000 },
    rating: 4.5,
    reviews: 890,
    tag: ["classic"],
  },

  {
    id: 46,
    title: "total recall",
    author: "Arnold Schwarzenegger",
    header: "my unbelievably true life story",
    subheader:
      "the autobiography of a man who dreamed the impossible — and did it",
    description:
      "arnold schwarzenegger tells the story of his three great careers: as a bodybuilding champion, as a box-office star, and as a powerful politician. he shares his unique approach to life and how he turned his dreams into reality — from immigrating to america with nothing to becoming one of the most recognizable people on the planet.",
    coverImage: "",
    primaryCollection: "lead him",
    collections: ["lead him", "lead with legacy"],
    genre: "memoir",
    price: { paperback: 1900000, hardback: 3000000 },
    rating: 4.6,
    reviews: 1200,
    tag: ["bestseller"],
  },

  {
    id: 47,
    title: "i am malala",
    author: "Malala Yousafzai",
    header: "the girl who stood up for education and was shot by the taliban",
    subheader: "one child, one teacher, one book, one pen can change the world",
    description:
      "when the taliban took control of the swat valley in pakistan, one girl spoke out. malala yousafzai refused to be silenced and fought for her right to an education. on october 9, 2012, she almost paid the ultimate price — shot in the head at point-blank range. this memoir is her extraordinary story of survival, resilience, and her mission to educate girls around the world.",
    coverImage: "",
    primaryCollection: "lead her",
    collections: ["lead her", "lead the young", "lead the world"],
    genre: "memoir",
    price: { paperback: 1500000, hardback: 2400000 },
    rating: 4.8,
    reviews: 2890,
    tag: ["top rated", "bestseller"],
  },

  {
    id: 48,
    title: "leaving the tarmac",
    author: "Aigboje Aig-Imoukhuede",
    header: "the most compelling business success story to come out of africa",
    subheader: "a memoir about building access bank",
    description:
      "aigboje aig-imoukhuede shares the behind-the-scenes story of transforming access bank from one of nigeria's most troubled banks into a continental powerhouse. part financial thriller, part leadership manual, this memoir offers unrivalled insight for anyone building a company or career in africa.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy", "lead them"],
    genre: "memoir",
    price: { paperback: 2000000, hardback: 3100000 },
    rating: 4.7,
    reviews: 310,
    tag: ["staff pick"],
  },

  {
    id: 49,
    title: "my own story",
    author: "Emmeline Pankhurst",
    header: "the memoir of the woman who won women the right to vote",
    subheader: "a story of courage, sacrifice, and conviction",
    description:
      "emmeline pankhurst's memoir tells the story of her leadership of the suffragette movement — the campaign to win women the right to vote in britain. it is a firsthand account of the hunger strikes, imprisonment, and the fierce determination that ultimately changed the law and the world.",
    coverImage: "",
    primaryCollection: "lead her",
    collections: ["lead her", "lead with legacy"],
    genre: "memoir",
    price: { paperback: 1500000, hardback: 2400000 },
    rating: 4.5,
    reviews: 320,
    tag: ["classic"],
  },

  {
    id: 50,
    title: "the story of my experiments with truth",
    author: "Mahatma Gandhi",
    header: "the autobiography of mahatma gandhi",
    subheader: "the story of one of history's greatest souls",
    description:
      "gandhi's autobiography traces his moral and spiritual development from childhood through the years he spent in south africa, where he developed his philosophy of nonviolent resistance. he describes his inner struggles as well as his public campaigns, offering a deeply personal account of a life dedicated to truth, justice, and service to humanity.",
    coverImage: "",
    primaryCollection: "lead with legacy",
    collections: ["lead with legacy", "lead me"],
    genre: "memoir",
    price: { paperback: 1700000, hardback: 2600000 },
    rating: 4.7,
    reviews: 1800,
    tag: ["classic"],
  },

  // ─────────────────────────────────────────
  // 📖 FICTION & STORYTELLING
  // ─────────────────────────────────────────

  {
    id: 51,
    title: "things fall apart",
    author: "Chinua Achebe",
    header: "the most widely read book in modern african literature",
    subheader: "a story of strength, culture, and the collision of worlds",
    description:
      "things fall apart is a classic narrative about africa's cataclysmic encounter with europe as it establishes a colonial presence on the continent. told through the experiences of okonkwo, a wealthy and fearful war hero, achebe explores how the ibo community in nigeria lived before and after the arrival of colonialism.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead the world"],
    genre: "fiction & storytelling",
    price: { paperback: 1500000, hardback: 2400000 },
    rating: 4.7,
    reviews: 5600,
    tag: ["classic"],
  },

  {
    id: 52,
    title: "americanah",
    author: "Chimamanda Ngozi Adichie",
    header: "a powerful story of love, race, and identity",
    subheader: "what does it mean to be black in america?",
    description:
      "ifemelu and obinze are young and in love when they depart military-ruled nigeria for the west. beautiful, self-assured ifemelu heads for america, where despite her academic success, she is forced to grapple with what it means to be black for the first time. a powerful, funny, and tender story about race, gender, and identity.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead her", "lead the world"],
    genre: "fiction & storytelling",
    price: { paperback: 1700000, hardback: 2600000 },
    rating: 4.6,
    reviews: 2300,
    tag: ["classic", "staff pick"],
  },

  {
    id: 53,
    title: "purple hibiscus",
    author: "Chimamanda Ngozi Adichie",
    header: "a stunning debut about faith, family, and the courage to speak",
    subheader: "a story of love, faith, and freedom",
    description:
      "fifteen-year-old kambili and her older brother jaja lead a privileged life in enugu, nigeria — beautiful house, prestigious schools, wealthy father. but their comfortable existence is nothing but a facade. their father rules his home with terror. this searing novel asks: what does it cost to stay silent?",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead her"],
    genre: "fiction & storytelling",
    price: { paperback: 1600000, hardback: 2500000 },
    rating: 4.6,
    reviews: 1800,
    tag: ["classic"],
  },

  {
    id: 54,
    title: "half of a yellow sun",
    author: "Chimamanda Ngozi Adichie",
    header: "winner of the orange broadband prize for fiction",
    subheader:
      "a story of love and loss set against the backdrop of the biafran war",
    description:
      "with astonishing vividness, chimamanda ngozi adichie recreates a seminal moment in modern african history — the biafran war of the late 1960s. her sweeping story of love and war follows three characters through the turbulence of the conflict, exploring the human costs of political ambition and the enduring power of love.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead the world"],
    genre: "fiction & storytelling",
    price: { paperback: 1700000, hardback: 2600000 },
    rating: 4.7,
    reviews: 2100,
    tag: ["classic", "top rated"],
  },

  {
    id: 55,
    title: "the alchemist",
    author: "Paulo Coelho",
    header: "a fable about following your dream",
    subheader: "every soul has its own destiny",
    description:
      "paulo coelho's masterpiece tells the mystical story of santiago, an andalusian shepherd boy who yearns to travel in search of worldly treasure. his quest will lead him to riches far different — and far more satisfying — than he ever imagined. santiago's journey teaches us about the essential wisdom of listening to our hearts.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead me"],
    genre: "fiction & storytelling",
    price: { paperback: 1500000, hardback: 2300000 },
    rating: 4.7,
    reviews: 5600,
    tag: ["classic", "bestseller"],
  },

  {
    id: 56,
    title: "animal farm",
    author: "George Orwell",
    header: "the timeless political fable",
    subheader: "a fairy story",
    description:
      "george orwell's brilliant, timeless political fable about a group of animals who overthrow their human farmer — only to find themselves living under an even more oppressive regime. animal farm is a warning about the corrupting nature of power and the ways in which revolutions can betray their own ideals.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead the world"],
    genre: "fiction & storytelling",
    price: { paperback: 1300000, hardback: 2200000 },
    rating: 4.5,
    reviews: 6800,
    tag: ["classic"],
  },

  {
    id: 57,
    title: "who moved my cheese",
    author: "Spencer Johnson",
    header: "an amazing way to deal with change in your work and in your life",
    subheader: "a simple parable that reveals profound truths",
    description:
      "this simple parable about four characters looking for cheese in a maze has become one of the most read business books in the world. cheese is a metaphor for what you want to have in life — and the story reveals profound truths about how to deal with change, let go of fear, and move forward when everything you depend on is taken away.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead me", "lead them"],
    genre: "fiction & storytelling",
    price: { paperback: 1200000, hardback: 2000000 },
    rating: 4.5,
    reviews: 2300,
    tag: ["classic"],
  },

  {
    id: 58,
    title: "the monk who sold his ferrari",
    author: "Robin Sharma",
    header: "a fable about fulfilling your dreams and reaching your destiny",
    subheader: "a parable about following your passion and living with purpose",
    description:
      "this inspiring tale about a fictional lawyer named julian mantle delivers a powerful message about the importance of self-leadership, personal responsibility, and living life with purpose. after a spiritual journey to india, julian returns to share the 7 timeless virtues for living your best life.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead me"],
    genre: "fiction & storytelling",
    price: { paperback: 1600000, hardback: 2500000 },
    rating: 4.4,
    reviews: 1900,
    tag: ["bestseller"],
  },

  {
    id: 59,
    title: "weep not, child",
    author: "Ngũgĩ wa Thiong'o",
    header: "the first english-language novel published by an east african",
    subheader:
      "a moving story about the effects of colonialism on one kenyan family",
    description:
      "set in kenya during the mau mau uprising of the 1950s, weep not, child traces the devastating effects of colonial rule on a family and a community. through the eyes of njoroge — a young boy desperate for education and a brighter future — ngũgĩ wa thiong'o chronicles the dispossession and heartbreak of a people fighting for their land and freedom.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead the world"],
    genre: "fiction & storytelling",
    price: { paperback: 1400000, hardback: 2300000 },
    rating: 4.5,
    reviews: 980,
    tag: ["classic"],
  },

  {
    id: 60,
    title: "the five dysfunctions of a team",
    author: "Patrick Lencioni",
    header: "a leadership fable",
    subheader: "the #1 bestseller on teamwork",
    description:
      "in this remarkable book, patrick lencioni offers a leadership fable that is as enthralling and instructive as his previous bestsellers. he turns his storytelling power to the fascinating, complex world of teams — asking why some teams fail to work together, and how leaders and team members can overcome these all-too-human tendencies.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead them"],
    genre: "fiction & storytelling",
    price: { paperback: 1700000, hardback: 2600000 },
    rating: 4.6,
    reviews: 1500,
    tag: ["bestseller"],
  },

  {
    id: 61,
    title: "siddhartha",
    author: "Hermann Hesse",
    header: "a classic of world literature",
    subheader: "the timeless story of a soul's journey toward truth",
    description:
      "siddhartha is the story of a young brahmin's search for ultimate enlightenment after meeting with the buddha. this deeply spiritual and luminous tale follows its hero as he travels from pleasure to asceticism, from love to solitude, from wealth to poverty, in his quest for wisdom and self-knowledge.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead me"],
    genre: "fiction & storytelling",
    price: { paperback: 1300000, hardback: 2200000 },
    rating: 4.6,
    reviews: 3800,
    tag: ["classic"],
  },

  {
    id: 62,
    title: "1984",
    author: "George Orwell",
    header: "one of the most thought-provoking novels of the 20th century",
    subheader: "big brother is watching you",
    description:
      "george orwell's haunting prophecy about the future has become one of the most influential books ever written. in the year 1984, winston smith lives under a totalitarian government that controls every aspect of life, even thought. it remains the most powerful warning against the dangers of totalitarianism and the destruction of truth ever written.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead the world"],
    genre: "fiction & storytelling",
    price: { paperback: 1400000, hardback: 2300000 },
    rating: 4.7,
    reviews: 9200,
    tag: ["classic"],
  },

  {
    id: 63,
    title: "stay with me",
    author: "Ayọ̀bámi Adébáyọ̀",
    header: "shortlisted for the 2017 bailey's women's prize for fiction",
    subheader:
      "a devastating story of love, marriage, and the limits of sacrifice",
    description:
      "unravelling against the social and political turbulence of 1980s nigeria, stay with me tells the story of yejide and akin — a couple whose marriage buckles under the weight of family pressure and the desperate need to have a child. ayọ̀bámi adébáyọ̀ weaves a devastating story of married love, grief, and the bonds of motherhood.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead her"],
    genre: "fiction & storytelling",
    price: { paperback: 1600000, hardback: 2500000 },
    rating: 4.3,
    reviews: 1200,
    tag: ["staff pick"],
  },

  {
    id: 64,
    title: "season of migration to the north",
    author: "Tayeb Salih",
    header: "the most important arabic novel of the 20th century",
    subheader: "a masterpiece of postcolonial literature",
    description:
      "a sudanese man returns home after years of studying in europe, only to find a stranger has settled in his village: mustafa sa'eed, a man with a mysterious past and a disturbing relationship to the west. this slim novel unpacks the legacy of colonialism on both the colonizer and the colonized, exploring identity, power, and belonging.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead the world"],
    genre: "fiction & storytelling",
    price: { paperback: 1500000, hardback: 2400000 },
    rating: 4.4,
    reviews: 760,
    tag: ["classic"],
  },

  {
    id: 65,
    title: "the secret lives of baba segi's wives",
    author: "Lola Shoneyin",
    header: "winner of the pen/open book award",
    subheader: "a bold, darkly comic novel about polygamy, power, and secrets",
    description:
      "when isola bello — known as baba segi — takes a fourth wife, the fragile peace of his household is shattered. lola shoneyin's debut is a fierce and funny novel about power, womanhood, and survival in contemporary nigeria.",
    coverImage: "",
    primaryCollection: "lead with imagination",
    collections: ["lead with imagination", "lead her"],
    genre: "fiction & storytelling",
    price: { paperback: 1600000, hardback: 2500000 },
    rating: 4.4,
    reviews: 890,
    tag: ["staff pick"],
  },

  // ─────────────────────────────────────────
  // 👶 CHILDREN'S BOOKS
  // ─────────────────────────────────────────

  {
    id: 66,
    title: "oh, the places you'll go!",
    author: "Dr. Seuss",
    header: "the perfect gift for any milestone in life",
    subheader: "life's journey begins with one step",
    description:
      "in this joyful ode to life, dr. seuss addresses life's ups and downs with his signature good humor. a beloved gift for graduations and new beginnings, it reminds readers that they have brains in their head and feet in their shoes — and they can steer themselves any direction they choose.",
    coverImage: "",
    primaryCollection: "lead little ones",
    collections: ["lead little ones", "lead me"],
    genre: "children's books",
    price: { paperback: 1200000, hardback: 2000000 },
    rating: 4.9,
    reviews: 6700,
    tag: ["classic", "bestseller"],
  },

  {
    id: 67,
    title: "the little engine that could",
    author: "Watty Piper",
    header: "the classic tale of optimism and hard work",
    subheader: "i think i can, i think i can",
    description:
      "a little engine is asked to pull a long train over a mountain after several larger engines refuse. the little engine agrees to try, repeating the encouraging mantra 'i think i can'. this american classic has been used for generations to teach children the value of optimism, persistence, and hard work.",
    coverImage: "",
    primaryCollection: "lead little ones",
    collections: ["lead little ones", "lead me"],
    genre: "children's books",
    price: { paperback: 1000000, hardback: 1800000 },
    rating: 4.8,
    reviews: 3200,
    tag: ["classic"],
  },

  {
    id: 68,
    title: "matilda",
    author: "Roald Dahl",
    header:
      "a funny story about a girl who discovers she has remarkable powers",
    subheader: "never underestimate a small girl with a big brain",
    description:
      "matilda is a little girl who is far too good to be true. at age five-and-a-half she's knocking off double-digit multiplication problems and has read every book in the library. her parents think she's a nuisance. but matilda is a delight — the story of a small, extraordinary girl who fights back against the forces of ignorance and cruelty.",
    coverImage: "",
    primaryCollection: "lead little ones",
    collections: ["lead little ones", "lead her"],
    genre: "children's books",
    price: { paperback: 1100000, hardback: 1900000 },
    rating: 4.9,
    reviews: 4500,
    tag: ["classic", "bestseller"],
  },

  {
    id: 69,
    title: "the giving tree",
    author: "Shel Silverstein",
    header: "a tender story about the relationship between people and nature",
    subheader: "a story of love that has never stopped giving",
    description:
      "once there was a tree who loved a little boy. and every day the boy would come and the tree would give him everything she had — her apples, her branches, her trunk — and the tree was happy. a simple but profound story about giving, generosity, and the true meaning of love.",
    coverImage: "",
    primaryCollection: "lead little ones",
    collections: ["lead little ones", "lead us"],
    genre: "children's books",
    price: { paperback: 1000000, hardback: 1800000 },
    rating: 4.7,
    reviews: 5100,
    tag: ["classic"],
  },

  {
    id: 70,
    title: "charlotte's web",
    author: "E.B. White",
    header: "one of the most beloved children's books ever written",
    subheader: "a story of friendship, loyalty, and what really matters",
    description:
      "this is the story of a little girl named fern who loved a little pig named wilbur — and of wilbur's devoted friend, a spider named charlotte. e.b. white's timeless tale of friendship, loyalty, and love is considered one of the finest books ever written for children.",
    coverImage: "",
    primaryCollection: "lead little ones",
    collections: ["lead little ones"],
    genre: "children's books",
    price: { paperback: 1000000, hardback: 1800000 },
    rating: 4.8,
    reviews: 4200,
    tag: ["classic"],
  },

  {
    id: 71,
    title: "anansi the spider",
    author: "Gerald McDermott",
    header: "a tale from the ashanti people of west africa",
    subheader: "a classic west african folktale about the trickster spider",
    description:
      "in this caldecott honor book, gerald mcdermott brings the traditional west african tale of anansi the spider to vivid life with bold, striking artwork. anansi is the great spider of ashanti tradition — a clever trickster whose adventures have been told across generations throughout west africa and the caribbean.",
    coverImage: "",
    primaryCollection: "lead little ones",
    collections: ["lead little ones", "lead the world"],
    genre: "children's books",
    price: { paperback: 1100000, hardback: 1900000 },
    rating: 4.5,
    reviews: 980,
    tag: ["classic"],
  },

  {
    id: 72,
    title: "sulwe",
    author: "Lupita Nyong'o",
    header: "a new york times bestseller",
    subheader: "a story about beauty, colorism, and self-acceptance",
    description:
      "sulwe has skin the color of midnight. she is darker than everyone in her family. darker than anyone in her school. sulwe just wants to be beautiful and bright, like her mother and sister. then a magical journey in the night sky opens her eyes and changes everything. a powerful story about colorism, self-acceptance, and the true meaning of beauty.",
    coverImage: "",
    primaryCollection: "lead little ones",
    collections: ["lead little ones", "lead her"],
    genre: "children's books",
    price: { paperback: 1300000, hardback: 2100000 },
    rating: 4.9,
    reviews: 2100,
    tag: ["bestseller", "staff pick"],
  },

  {
    id: 73,
    title: "ubuntu",
    author: "Leah Henderson",
    header:
      "a beautiful picture book celebrating the african philosophy of community",
    subheader: "i am because we are",
    description:
      "inspired by the african philosophy of ubuntu — the belief that we are all connected and that community is the foundation of a good life — this beautifully illustrated picture book teaches young readers the importance of kindness, sharing, and looking out for one another.",
    coverImage: "",
    primaryCollection: "lead little ones",
    collections: ["lead little ones", "lead us"],
    genre: "children's books",
    price: { paperback: 1100000, hardback: 1900000 },
    rating: 4.6,
    reviews: 430,
    tag: ["staff pick", "new arrival"],
  },

  {
    id: 74,
    title: "the very hungry caterpillar",
    author: "Eric Carle",
    header: "one of the best-loved picture books of all time",
    subheader: "a classic story of transformation",
    description:
      "the very hungry caterpillar has delighted a generation of readers. eric carle's iconic tale follows a tiny caterpillar as he eats through a variety of foods before transforming into a butterfly — teaching young children about counting, the days of the week, and the wonder of metamorphosis.",
    coverImage: "",
    primaryCollection: "lead little ones",
    collections: ["lead little ones"],
    genre: "children's books",
    price: { paperback: 900000, hardback: 1700000 },
    rating: 4.9,
    reviews: 8200,
    tag: ["classic", "bestseller"],
  },

  {
    id: 75,
    title: "my rows and piles of coins",
    author: "Tololwa Mollel",
    header: "a coretta scott king honor book",
    subheader:
      "a beautiful african story about saving, dreaming, and determination",
    description:
      "in this award-winning picture book set in tanzania, a young boy named saruni saves every coin he earns to buy a bicycle so he can help his mother carry goods to market. this gentle, beautifully illustrated story teaches children about the value of money, savings, hard work, and the joy of reaching your goals.",
    coverImage: "",
    primaryCollection: "lead little ones",
    collections: ["lead little ones", "lead with money"],
    genre: "children's books",
    price: { paperback: 1000000, hardback: 1800000 },
    rating: 4.6,
    reviews: 560,
    tag: ["staff pick"],
  },

  // ─────────────────────────────────────────
  // 🧒 YOUNG ADULT
  // ─────────────────────────────────────────

  {
    id: 76,
    title: "i am malala",
    author: "Malala Yousafzai",
    header: "the girl who stood up for education and was shot by the taliban",
    subheader: "one child, one teacher, one book, one pen can change the world",
    description:
      "when the taliban took control of the swat valley in pakistan, one girl spoke out. malala yousafzai refused to be silenced and fought for her right to an education. on october 9, 2012, she almost paid the ultimate price — shot in the head at point-blank range. her extraordinary story is a call to action for every young person who believes in the power of education.",
    coverImage: "",
    primaryCollection: "lead the young",
    collections: ["lead the young", "lead her", "lead the world"],
    genre: "young adult",
    price: { paperback: 1500000, hardback: 2400000 },
    rating: 4.8,
    reviews: 2890,
    tag: ["top rated", "bestseller"],
  },

  {
    id: 77,
    title: "the diary of a young girl",
    author: "Anne Frank",
    header: "the most widely read account of the holocaust",
    subheader:
      "in spite of everything, i still believe that people are truly good at heart",
    description:
      "anne frank's diary, written while she was hiding with her family from the nazis in amsterdam, is one of the most moving documents of the twentieth century. in it she writes about her fears, her hopes, her first love, and her dreams — all while living in constant danger of discovery.",
    coverImage: "",
    primaryCollection: "lead the young",
    collections: ["lead the young", "lead her"],
    genre: "young adult",
    price: { paperback: 1400000, hardback: 2300000 },
    rating: 4.8,
    reviews: 7800,
    tag: ["classic", "top rated"],
  },

  {
    id: 78,
    title: "to kill a mockingbird",
    author: "Harper Lee",
    header: "winner of the pulitzer prize",
    subheader: "the most celebrated novel of the american south",
    description:
      "harper lee's pulitzer prize-winning masterwork of honor and injustice in the deep south — and the heroism of one man in the face of blind and violent hatred. through the innocent eyes of scout and jem finch, we see their father atticus finch challenge a racist society and defend an innocent black man against an unjust charge.",
    coverImage: "",
    primaryCollection: "lead the young",
    collections: ["lead the young", "lead the world"],
    genre: "young adult",
    price: { paperback: 1500000, hardback: 2400000 },
    rating: 4.8,
    reviews: 9500,
    tag: ["classic", "top rated"],
  },

  {
    id: 79,
    title: "wonder",
    author: "R.J. Palacio",
    header:
      "the phenomenal #1 bestseller with over 12 million copies sold worldwide",
    subheader: "you can't blend in when you were born to stand out",
    description:
      "august pullman was born with a facial difference that, up until now, has prevented him from going to a mainstream school. starting fifth grade at beecher prep, he wants nothing more than to be treated as an ordinary kid. wonder shows us what it means to be extraordinary — and that each of us has the power to choose kindness.",
    coverImage: "",
    primaryCollection: "lead the young",
    collections: ["lead the young", "lead me"],
    genre: "young adult",
    price: { paperback: 1500000, hardback: 2400000 },
    rating: 4.8,
    reviews: 5400,
    tag: ["bestseller", "top rated"],
  },

  {
    id: 80,
    title: "tuesdays with morrie",
    author: "Mitch Albom",
    header: "an old man, a young man, and life's greatest lesson",
    subheader: "the book that changed millions of lives",
    description:
      "maybe it was a sportswriter's farewell to his old professor who was dying. or maybe it was a book about the most important things in life — love, work, community, family, aging, forgiveness, and, finally, death. mitch albom's memoir of his weekly visits with morrie schwartz has become one of the most beloved books of our time.",
    coverImage: "",
    primaryCollection: "lead the young",
    collections: ["lead the young", "lead me"],
    genre: "young adult",
    price: { paperback: 1400000, hardback: 2300000 },
    rating: 4.7,
    reviews: 4100,
    tag: ["classic", "bestseller"],
  },

  {
    id: 81,
    title: "long way down",
    author: "Jason Reynolds",
    header: "a national book award finalist",
    subheader:
      "a powerful novel in verse about gun violence and the cycle of revenge",
    description:
      "will has just watched his brother shawn get shot and killed. gripping the gun he plans to use to avenge his brother's death, will gets into an elevator and during that sixty-second ride, confronts five people from his past — each with a story of the same gun, the same cycle of violence.",
    coverImage: "",
    primaryCollection: "lead the young",
    collections: ["lead the young", "lead him"],
    genre: "young adult",
    price: { paperback: 1400000, hardback: 2300000 },
    rating: 4.6,
    reviews: 1900,
    tag: ["staff pick"],
  },

  {
    id: 82,
    title: "children of blood and bone",
    author: "Tomi Adeyemi",
    header: "the west african-inspired fantasy that took the world by storm",
    subheader:
      "they killed my mother. they took our magic. they tried to bury us.",
    description:
      "tomi adeyemi conjures a stunning world of dark magic and danger in her west african-inspired fantasy. zélie adebola remembers when the soil of orïsha hummed with magic — before the king's soldiers slaughtered all the maji and stripped magic from the land. now zélie has one chance to bring magic back and reclaim her people's power.",
    coverImage: "",
    primaryCollection: "lead the young",
    collections: ["lead the young", "lead with imagination", "lead the world"],
    genre: "young adult",
    price: { paperback: 1600000, hardback: 2500000 },
    rating: 4.6,
    reviews: 1900,
    tag: ["bestseller", "staff pick", "new arrival"],
  },

  {
    id: 83,
    title: "akata witch",
    author: "Nnedi Okofor",
    header: "a west african harry potter — unlike anything you've ever read",
    subheader: "discover your power",
    description:
      "twelve-year-old sunny lives in nigeria but was born in new york. she is an albino and an outsider. but when she discovers she has supernatural abilities, she is initiated into the leopard society — a secret world of magic that has existed in africa for thousands of years. nnedi okofor's award-winning fantasy draws on yoruba mythology and african folklore.",
    coverImage: "",
    primaryCollection: "lead the young",
    collections: ["lead the young", "lead with imagination"],
    genre: "young adult",
    price: { paperback: 1500000, hardback: 2400000 },
    rating: 4.5,
    reviews: 1200,
    tag: ["staff pick", "new arrival"],
  },

  {
    id: 84,
    title: "so spoke the earth",
    author: "Various African Authors",
    header: "a powerful anthology from africa's brightest young voices",
    subheader: "stories that celebrate the diversity of the african experience",
    description:
      "so spoke the earth is a rich anthology of short fiction from across the african continent, celebrating the diversity and depth of the african experience. from the savannahs of east africa to the megacities of west africa, these stories explore identity, belonging, family, and what it means to be young and african in the modern world.",
    coverImage: "",
    primaryCollection: "lead the young",
    collections: ["lead the young", "lead the world"],
    genre: "young adult",
    price: { paperback: 1500000, hardback: 2400000 },
    rating: 4.4,
    reviews: 340,
    tag: ["staff pick", "new arrival"],
  },

  {
    id: 85,
    title: "the outsiders",
    author: "S.E. Hinton",
    header:
      "the iconic international bestseller with over 25 million copies sold",
    subheader:
      "a heroic coming-of-age story about friendship, loyalty, and belonging",
    description:
      "ponyboy curtis knows he can count on his brothers and his friends — true friends who would do anything for him. but not on much else besides trouble with the socs, a vicious gang of rich kids whose idea of a good time is beating up on greasers like ponyboy. when the conflict between the groups results in death, ponyboy must choose between his loyalty and his sense of right and wrong.",
    coverImage: "",
    primaryCollection: "lead the young",
    collections: ["lead the young", "lead me"],
    genre: "young adult",
    price: { paperback: 1400000, hardback: 2200000 },
    rating: 4.7,
    reviews: 4100,
    tag: ["classic"],
  },
];
